### ISSUE TITLE
temperature tables

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/flow-framework#174]
Please rewrite these in golang 

https://github.com/NubeIO/lora-raw/pull/124/files#diff-e8631a24e3c8a5d2ee38eabe5869ba157ee5e1c60f4c7e635b09b1f248c8db07R61

Add them in here
https://github.com/NubeIO/nubeio-rubix-lib-helpers-go

**Comment by bashyftw** [comment]
Hi Marc,
This is a lookup table with linear interpolated between points.
If you have any questions give me a call.

**Comment by CanuckMarc** [comment]
@NubeDev This is done.  Check it out here: https://github.com/NubeIO/nubeio-rubix-lib-helpers-go/pull/1
