### ISSUE TITLE
Schedule Model

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/flow-framework#329]

**Comment by CanuckMarc** [comment]
@RaiBnod 

The new schedule JSON should be the following format:


```
{
  "events":                                                               <---  EVENTS TYPE
  {
    "59201e03-7356-4687-911f-c0840d666666":    <--- Random UUID, could be much shorter.
    {
      "name": "HVAC",
      "dates":
      [
        {
          "start": "2021-12-16T03:00:00.000Z",           <--- Timestamps in UTC
          "end": "2021-12-16T04:00:00.000Z"
        }
      ],
      "value": 20,
      "color": "#d0021b"
    }
  },
  "weekly":                                                               <---  WEEKLY TYPE.  All days and times are in LOCAL TIME. 
  {
    "919d7b4c-2540-4759-bb29-afc017ed03c7":    <--- Random UUID, could be much shorter.
    {
      "name": "HVAC",
      "days":  <---  LOCAL DAYS, NOT UTC
      [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday"
      ],
      "start": "09:00",  <---  LOCAL TIME, NOT UTC
      "end": "13:00",  <---  LOCAL TIME, NOT UTC
      "value": 20,
      "color": "#4a90e2",
      "timezone": "Australia/Sydney"  <---  LOCAL TIMEZONE
    }
  },
  "exceptions":                                                               <---  EXCEPTIONS TYPE,  same formats as EVENTS schedules.
  {
    "59201e03-7356-4687-911f-c0840dad4977":    <--- Random UUID, could be much shorter.
    {
      "name": "HVAC",
      "dates":
      [
        {
          "start": "2021-12-16T01:00:00.000Z",           <--- Timestamps in UTC
          "end": "2021-12-16T08:00:00.000Z"
        },
        {
          "start": "2021-12-10T01:00:00.000Z",
          "end": "2021-12-10T03:00:00.000Z"
        }
      ],
      "value": 0,
      "color": "#d0021b"
    }
  }
}
```

**Comment by RaiBnod** [comment]
Here,

- Making that UUID small makes sense, we'll do it.
- All dates will be on `UTC`, making some dates on `UTC` and some on `local dates` is leads to confusion, and setting local dates on DB is bad practice as well.
   - while computing time on the device, we just convert those dates as per the device's timezone (for example, if the device is on `AEST+10:00`, we subtract that time by 10 hrs that's it).
- The above example of an exception is an exact replication of events. But that exception is for `Holiday` which doesn't depend on Timezone. 
   - while computing DateTime on the device, it needs to be the whole day from 00:00 to 23:59 59s of that device. And while we show it on UI it needs to be rendered on a whole day, for example: on 25th Dec, it needs to be shown the whole day as `Holiday` on UI. And needs to be calculated on the device in the same way.
   
So, our final schema will be like this:

```JSON
{
  "events": {
    "59201e03": {
      "name": "HVAC",
      "dates": [
        {
          "start": "2021-12-16T03:00:00.000Z",
          "end": "2021-12-16T04:00:00.000Z"
        }
      ],
      "value": 20,
      "color": "#d0021b"
    }
  },
  "weekly": {
    "919d7b4c": {
      "name": "HVAC",
      "days": [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday"
      ],
      "start": "09:00",
      "end": "13:00",
      "value": 20,
      "color": "#4a90e2"
    }
  },
  "exceptions": {
    "59201e03": {
      "name": "Hall",
      "date": "12-25",
      "value": 22,
      "color": "#4a90e2"
    }
  }
}
```

If you don't agree with this, you can put your concern. FYI, this schema is tested one as well, in UI as well as Device (wires).

**Comment by CanuckMarc** [comment]
@RaiBnod PLEASE FOLLOW MY SCHEDULE SCHEMA!  I have throught about it for a long time, and there is a reason for each decision i've made.  If you want to discuss we can, but please trust me.

- The `exceptions` should be exactly the same as the `events`.  They are the exact same type of schedule (start datetime -> end datetime, not just discrete days).  

- `weekly` schedules must be in local time.  It doesn't make any sense to store them in UTC.  They should not be saved as datetimes.  If you need a function that generates the next `x` number of start/stop times from a weekly schedule, I can write the function for you.   The issue here is DST offsets and the timechanges; it creates issues that are very difficult to solve with the exising time libraries in JS and GO.  Please explain your issues with using local time for `weekly` schedules if you want to discuss further.  I understand that most schedules are dealt with in UTC, but most schedules are not recurring/weekly schedules, they are a different thing entirely.

**Comment by RaiBnod** [comment]
> The exceptions should be exactly the same as the events. They are the exact same type of schedule (start datetime -> end datetime, not just discrete days).

If exceptions should be the same as events, why do we need them as a different event type? We drop this feature then.

**Comment by CanuckMarc** [comment]
@RaiBnod No, they are treated differently when the Schedule JSON is decoded.  The format of the `events` and `exceptions` is the same.

**Comment by CanuckMarc** [comment]
@RaiBnod  thanks for the chat.  Please post the Schedule JSON schema description here.  I will work on updating the Schedule Checker plugin code to match.

**Comment by RaiBnod** [comment]
We conclude our schema like this one:
```JSON
{
  "events": {
    "59201e03": {
      "name": "HVAC",
      "dates": [
        {
          "start": "2021-12-16T03:00:00.000Z",
          "end": "2021-12-16T04:00:00.000Z"
        }
      ],
      "value": 20,
      "color": "#d0021b"
    }
  },
  "weekly": {
    "919d7b4c": {
      "name": "HVAC",
      "days": [
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday"
      ],
      "start": "09:00",
      "end": "13:00",
      "value": 20,
      "color": "#4a90e2"
    }
  },
  "exceptions": {
    "34501ab2": {
      "name": "Christmas",
      "dates": [
        {
          "start": "2021-12-16T03:00:00.000Z",
          "end": "2021-12-16T04:00:00.000Z"
        }
      ],
      "value": 20,
      "color": "#d0021b"
    }
  },
  "timezone": "Australia/Sydney"
}
```

All of the dates and times will be in the local timezone. This is because of Daylight saving time (DST) support.

**Comment by CanuckMarc** [comment]
@RaiBnod Just a couple of notes on the Schedule JSON Schema:

1. `"scheudles": {` is incorrectly spelled, please make sure it's `schedules` 
2. For timestamp please make sure all `month`, `day` `hour` and `minute` values always have 2 characters in the timestamp string (`"2022-2-4T7:00"` --> `"2022-02-04T07:00"`).  `year` should have 4 characters.
3. Could you explain what the `names` config property will be used for?  I assume it will hold all the possible `Schedule Names`.  Just wanted to know how it would be used in the UI.

**Comment by RaiBnod** [comment]
Have you tried it on FF through wires-plat?

Writers output example is like this:

```JSON
{
  "uuid": "wri_caba1f4658de49d3",
  "sync_uuid": "ba411a09db6c4a64",
  "writer_thing_class": "schedule",
  "writer_thing_uuid": "sch_96936f59a9c94e93",
  "writer_thing_name": "ARMADALE-83662",
  "data_store": {
    "schedules": {
      "events": {
        "h7cbZCPh4wxuDz69ZTLuQx": {
          "name": "Event",
          "dates": [
            {
              "start": "2022-02-02T00:00",
              "end": "2022-02-02T01:00"
            }
          ],
          "value": 18,
          "color": "#FF0000FF"
        }
      },
      "weekly": {
        "dGpBRgq5ENrKoxvJr2XzD6": {
          "name": "Weekly",
          "days": [
            "sunday",
            "monday"
          ],
          "start": "00:00",
          "end": "02:00",
          "value": 12,
          "color": "#FF0000FF"
        }
      },
      "exception": {
        "8vSLmdx4E8Mpe2dqREcYa2": {
          "name": "Exception",
          "dates": [
            {
              "start": "2022-02-04T00:00",
              "end": "2022-02-04T01:00"
            }
          ],
          "value": 25,
          "color": "#FF0000FF"
        }
      }
    },
    "config": {
      "timezone": "Asia/Katmandu",
      "names": {
        "0abf73d8-28a4-4084-9523-de7db415299c": {
          "id": "0abf73d8-28a4-4084-9523-de7db415299c",
          "name": "Event"
        },
        "80d16850-dd04-45a7-9f9b-e123ebba4bc3": {
          "id": "80d16850-dd04-45a7-9f9b-e123ebba4bc3",
          "name": "Exception"
        },
        "18d99bdf-0897-49d4-a60c-cfdc49d84f3c": {
          "id": "18d99bdf-0897-49d4-a60c-cfdc49d84f3c",
          "name": "Weekly"
        }
      }
    }
  },
  "created_on": "2021-12-31T01:14:26.083712682Z",
  "updated_on": "2022-02-04T03:10:29.423952179Z",
  "consumer_uuid": "con_19a5ddd7c11c4542"
}
```

- So, your 1, 2 concerns for those defects don't exist in our system. You just pick the `data_store` key's value from there.
- For 3. that `names` is just a config used for the frontend.
- Also, nothing to do with `timezone` on your side. That's just to show the frontend for which timezone this schedule is set. We don't do any calculation on the frontend, same as you do nothing with that timezone. Just calculate on the basis of your edge device OS local timezone.

Hence, `data_store.schedules` is only useful on your side.

**Comment by CanuckMarc** [comment]
Schedule JSON format is detailed here: https://github.com/NubeIO/flow-framework/wiki/Schedule
