### ISSUE TITLE
Migration issue on TimescaleDB

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/flow-framework#534]
Works fine on PostgreSQL. But we have the issue with migrating TimescaleDB.

See that issue, it continues to never-ending queries again and again:

https://user-images.githubusercontent.com/6800775/176662369-c3a01cd1-bbca-4d26-be8b-83fdd5cbf68b.mov

**Comment by enjuthulung** [comment]
Its not a never-ending issue, Its just taking a lot of time to run migration. (SLOW SQL issue)
