### ISSUE TITLE
Move Polling Queue code to a library

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/flow-framework#572]
Back when i started, to keep things simple, I built the Poll Queue into the modbus plugin itself.  But now i'd ideally like to move the polling queue code to a seperate library so that it can be re-used for bacnet and other plugins.  

@RaiBnod  Can you advise the best way to go about moving this code to a seperate library?

The Poll Queue code is all here: https://github.com/NubeIO/flow-framework/tree/master/plugin/nube/protocals/modbus/pollqueue

**Comment by RaiBnod** [comment]
Ya, it needs to move to a library and can be able to use in multiple places without any issues and conflicts.

**Comment by CanuckMarc** [comment]
@RaiBnod If your backend developer is free to move the polling queue to a library, please have him go ahead.  All my changes are included in master to-date.

**Comment by CanuckMarc** [comment]
@enjuthulung do you have an ETA on the completion of this task?  My next task is to add the `pollingQueue` functions to other plugins (BACnet, etc), so the functions need to be in a re-usable library first.

**Comment by enjuthulung** [comment]
@CanuckMarc found some Database methods (DBHandlerRef.GetNetwork(), DBHandlerRef.UpdatePoint()) and unclear functions scope (public/private) which makes harder to make this as a library. By passing data(ie; network,devices,points..) in methods and clarifying functions scope, we can make it library however it is a bit complex and time consuming.
_Alternative: We can make this a service and reuse the code._

**Comment by CanuckMarc** [comment]
@enjuthulung 

Can you explain how a `service` would be implemented?

Would this make it easier if I seperate the `Database Methods` out of all the code in the `pollqueue` folder (https://github.com/NubeIO/flow-framework/tree/master/plugin/nube/protocals/modbus/pollqueue)?  The database methods would be called from the plugin `app.go` methods.

**Comment by enjuthulung** [comment]
@CanuckMarc due to database dependency it is impossible to make pollqueue a library. Solution : https://github.com/NubeIO/flow-framework/pull/582 .  This is similar to https://github.com/NubeIO/flow-framework/pull/580 , only the location can't be utils.

**Comment by CanuckMarc** [comment]
Thanks.  I've included your changes into my branch, and i'll merge it shortly.   Closing your PR as all changes have been included.
