### ISSUE TITLE
Producer History Settings to Point Settings

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/flow-framework#574]
I think we should find a way to promote the `producer history` settings into the `point` settings (so that the user doesn't need to drill down to the producer to change the history settings).  If there can be multiple producers per point (i don't know if this is possible) then we could show multiple history settings under the point settings.

**Comment by RaiBnod** [comment]
This has the central control for setting up producer history #594.

Hence closing down the ticket.
