### ISSUE TITLE
tag with key and value

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/flow-framework#653]
Make it so when can make the key name for the tags

so user can search for `nets` `devs` and `points` based of the tags and also the `histories`

```
/api/points/tags/?address=1234
```

```
/api/histories/tags/?address=1234
```

the histories would need to to return the data with the point key for each point that has that tag

```json
{
    "tags": [
        {
            "address": "1234"
        },
        {
            "myTag2": "hello-2"
        }
    ]
}
```

**Comment by Shiny380** [comment]
@NubeDev @RaiBnod This should be done as mapping/meta-data like Binod discussed.
I think it should be called "meta-data"

**Comment by Shiny380** [comment]
covered by #676
