### ISSUE TITLE
Create auto mapping between edge to cloud

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/flow-framework#675]
Needs to have features:
- Sync on the changes
- Resync if some changes are missing; it sync could get failed due to various reasons
- The edge device's point needs to map with the system plugin point on the cloud side --which needs to store all attributes

**Comment by Shiny380** [comment]
- Don't sync on COV of certain fields that can change a lot. i.e. "last_ok", "last_fail" timestamps and error messages
