### ISSUE TITLE
Improvement on Point write

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/flow-framework#847]
### Summary

Our plugins are doing excessive point update calls. This brings us to a stage where our SQL DB can't perform well and the database gets locked.

### Task

To resolve it, we need to create a `Point write API` which will be calling through plugins to update values on the `Points`. And have the following improvements on it:
- We either commit those values after a certain time, let's say 5 sec
- We save those values on the buffer and schedule the DB to write after a certain period of time (this seems more reliable, let's say if we get 100s calls for a point xyz in the scheduled time, it will take the latest value, and proceed for a single update call)

### Scope

- [ ] Need to create `Point write API` with the buffer implementation
- [ ] Need to call it from a plugin so other plugins can use it in the same way, those API call plugins could be either of these two:
   - bacnet
   - modbus

**Comment by NubeDev** [comment]
i think also polling uses a lot a DB writes
https://github.com/NubeIO/flow-framework/blob/master/plugin/nube/protocals/modbus/polling.go#L63
