### ISSUE TITLE
Trim names

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/flow-framework#872]
Trim networks, devices, and points names before inserting/updating them. Otherwise, untrimmed names would cause issues in multiple places. For an example: https://github.com/NubeIO/flow-framework/pull/870/commits/8f622ea12ca22153d887da9fa2517e5ab39f9eb0#diff-628cd7b8a64082b5eb813de4ee4df36463866e78114c29dd964a6098d96b26e8R101

If we don't un-trim it there will be an issue of: `connection reset by peer` and it will keep disconnecting and reconnecting.

**Comment by RaiBnod** [comment]
![image](https://user-images.githubusercontent.com/6800775/223773587-fcb12135-e423-4614-99c8-3a239589c6ea.png)

**Comment by NubeDev** [comment]
we need to allow the user a friendly name as it looks better in reports and webpages 

So can we just either add a new field or encode/decode the topics

**Comment by RaiBnod** [comment]
We are allowing users with spaces in between but just trimming the values. So, the name field itself is a user-friendly name.

The trim function should trim spaces, from prefixes and suffixes.
