### ISSUE TITLE
Prohibit `/` in names.  

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/flow-framework#953]
If we are using network/device/point names in MQTT topics, we cannot allow `/` in the names.  This will need to be prohibited in the backend.

**Comment by NubeDev** [comment]
the UI does already have this
https://github.com/NubeIO/rubix-ce/blob/d4158f3c7ff98ef54a5bc39678fb40d71e7f495e/backend/helpers/str/str.go#L9

**Comment by CanuckMarc** [comment]
Kester just tested this and was still able to add names with `/`

**Comment by NubeDev** [comment]
probs was old build

**Comment by CanuckMarc** [comment]
correct.  

I do think we should add something to FF to prevent it too.  Not just relying on the UI.

**Comment by RaiBnod** [comment]
@enjuthulung, also include this on our backend code.

**Comment by NubeDev** [comment]
> @enjuthulung, also include this on our backend code.
can you make it so we can add more checks as needed

like not supporting `#$%^&*()` and double spaces and so on

```
func CleanStringNames(s string) (string, error) {
	var errMessage string = "name can not contain any:"
	if s == "" {
		return "", errors.New(fmt.Sprintf("name can not be empty"))
	}
	if strings.Contains(s, "/") {
		return strings.ReplaceAll(s, "/", "-"), errors.New(fmt.Sprintf("%s / (backslash)", errMessage))
	}
	noSpaces := strings.Join(strings.Fields(s), " ")
	return noSpaces, nil
}
```
