### ISSUE TITLE
Schedule patch on v0.9.25

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/flow-framework#956]
for the events and exceptions we need to trim the seconds format that envizi send in the HTTP body

or we need to update evey edge device, so it think its better if we just update the master

i think they use the writer API
https://github.com/NubeIO/flow-framework/blob/b618d72248ea7a097884e4a7975a8c8968650275/api/writer.go#L69

**Comment by RaiBnod** [comment]
Closed by https://github.com/NubeIO/flow-framework/pull/958
