### ISSUE TITLE
Priority array is null for modbus

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/flow-framework#960]
It seems like, we are updating only the present value and original value, leaving the priority array blank. But we are using those priority arrays to update values on mapping. For example, `point1` and `point2` are mapped to each other we sync that priority array from `point1` to `point2` and vice-versa as in here:

- https://github.com/NubeIO/flow-framework/blob/2582b851c75299b40194a17e7a381b1e9e1b1986/database/producer.go#L256

![image](https://user-images.githubusercontent.com/6800775/234776870-50fa72dd-f208-420c-aa9e-99fab415731f.png)

So, either we need to update the priority array as well from the plugin or if the priority array is supposed to be null, we need to sync the present value on such mapping as well.

**Comment by CanuckMarc** [comment]
@RaiBnod 

The `PointPriorityArrayMode` property decides how the Points will use the priority array.  The `ReadOnlyNoPriorityArrayRequired` `PointPriorityArrayMode` type doesn't use the priority array at all.  
There are descriptions of the `PointPriorityArrayMode` types here:
https://github.com/NubeIO/nubeio-rubix-lib-models-go/blob/1e60a1eabaeb8380f4c4a8f24fba37ba8f429488/pkg/v1/model/points.go#L132
To sumarize tho:
- `PriorityArrayToPresentValue` - `highest priority value` --> `PresentValue`
- `PriorityArrayToWriteValue` - `highest priority value` --> `WriteValueOriginal` --> `WriteValue` --> (Write/Read from Other Device) -> `OriginalValue` --> `PresentValue`
- `ReadOnlyNoPriorityArrayRequired` - (Read from Other Device) -> `OriginalValue` --> `PresentValue`

I think the mapping should be updated to also map the `PresentValue` in addition to the Priority Array.  There are 2  `PointPriorityArrayMode` types where the `PresentValue` doesn't come directly from the Priority Array.
