### ISSUE TITLE
LoRaWAN - Not all values coming through from Chirpstack

### ISSUE THREAD

**Issue by kesteryau** [NubeIO/flow-framework#979]
@Shiny380 

This is on a client's PC, please notify me if you need access to his device.

No 'pushbutton' value is coming through on the Milesight button (push button). Only SNR and RSSI values are showing. 

**Chirpstack values**

![MS Button(chirpstack)](https://user-images.githubusercontent.com/60494496/234769001-ea55a42d-e8b7-46b9-9000-519b7df11868.PNG)

**Rubix CE values**

![MS Button](https://user-images.githubusercontent.com/60494496/234768995-7a3ce347-9af0-4112-9190-86be0d248314.PNG)

Not all the values from this Dragino IO module is showing in the Rubix CE page.

**Chirpstack values**

![Dragino (Chirpstack)](https://user-images.githubusercontent.com/60494496/234769674-6fa766bd-5998-4b8f-a2e7-dd9da90c3499.PNG)

**Rubix CE values**

![Dragino](https://user-images.githubusercontent.com/60494496/234769531-d13218ec-646e-4a73-810f-f5ae10dbf518.PNG)

**Comment by Shiny380** [comment]
Resolved by #985
